# Generated by Django 3.2.3 on 2021-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredpage',
            name='raw',
            field=models.BooleanField(default=False, help_text='If checked, will compare unparsed content of url', verbose_name='Raw content check?'),
        ),
    ]
